# Generated by Django 4.2.4 on 2023-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_image_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to='files'),
        ),
    ]
