# Generated by Django 4.2.4 on 2023-08-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_user_phone_user_approved_by_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_approved',
            new_name='is_active',
        ),
    ]
