# Generated by Django 4.2.4 on 2023-08-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename_is_approved_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
