# Generated by Django 4.2.4 on 2023-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_rename_user_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='is_active',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='approved_by_email',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
